<?php

namespace Modules\Plano\Repositories;

use Modules\Plano\Presenters\ContratacaoFaturaPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use Modules\Plano\Repositories\ContratacaoFaturaRepository;
use Modules\Plano\Models\ContratacaoFatura;
use Modules\Plano\Validators\ContratacaoFaturaValidator;

/**
 * Class ContratacaoFaturaRepositoryEloquent
 * @package namespace Modules\Plano\Repositories;
 */
class ContratacaoFaturaRepositoryEloquent extends BaseRepository implements ContratacaoFaturaRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return ContratacaoFatura::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }


    public function presenter()
    {
        return ContratacaoFaturaPresenter::class;// TODO: Change the autogenerated stub
    }
}
