<?php

namespace Modules\Transporte\Models;

use Illuminate\Database\Eloquent\Model;
use Modules\Core\Models\User;
use Modules\Transporte\Repositories\TipoDocumentoRepository;
use Modules\Transporte\Repositories\VeiculoRepository;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Veiculo extends Model implements Transformable
{

	const ACEITO = "aceito";
	const INVALIDO = "invalido";
	const PENDENTE = "pendente";

	use TransformableTrait;

    protected $fillable = [
        'user_id',
        'transporte_marca_carro_id',
        'transporte_modelo_carro_id',
        'placa',
        'observacao',
        'num_passageiro',
        'ano',
        'ano_modelo_fab',
        'cor',
        'renavam',
        'data_licenciamento',
        'tipo_combustivel',
        'consumo_medio',
        'chassi',
        'porta_mala_tamanho',
        'arquivo',
        'status',
        'habilitado',
    ];

    protected $table = 'transporte_veiculos';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $ativar = function ($query){
            if(!is_null($query->id)) {
                $validado = app(TipoDocumentoRepository::class)->validadeVeiculo($query->id);
                $query->status = (!$validado['habilitado']) ? Veiculo::PENDENTE : Veiculo::ACEITO;
                return $query;
            }
        };
        self::creating(function ($query) use ($ativar){
            return $ativar($query);
        });
        self::updating(function ($query) use ($ativar){
            return $ativar($query);
        });
        self::updated(function ($query){
            return $query->usuario->save();
        });
        self::saving(function ($query) use ($ativar){
            return $ativar($query);
        });
    }

    public function marca(){
        return $this->belongsTo(MarcaCarro::class, 'transporte_marca_carro_id');
    }

    public function modelo(){
        return $this->belongsTo(ModeloCarro::class, 'transporte_modelo_carro_id');
    }

    public function usuario(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function documento()
    {
        return $this->morphMany(Documento::class, 'documentotable')->join('transporte_tipo_documentos','transporte_tipo_documentos.id','transporte_documentos.transporte_tipo_documento_id')->orderBy('transporte_tipo_documentos.nome','ASC')->select(['transporte_documentos.*']);
    }

    public function clrvAtivo(){
		return $this->morphOne(Documento::class, 'documentotable')->where('transporte_tipo_documento_id', '=', Documento::CLRV_ID)->where('status', '=', Documento::STATUS_ACEITO);
	}

    public function vistoriaAtivo(){
		return $this->morphOne(Documento::class, 'documentotable')->where('transporte_tipo_documento_id', '=', Documento::VISTORIA_ID)->where('status', '=', Documento::STATUS_ACEITO);
	}

    public function seguroAtivo(){
		return $this->morphOne(Documento::class, 'documentotable')->where('transporte_tipo_documento_id', '=', Documento::SEGURO_ID)->where('status', '=', Documento::STATUS_ACEITO);
	}

}
